import {
  Wrench,
  Shower,
  Drop,
  Building,
  Flame,
  Wind,
  Funnel,
  Warning,
  MapPin,
  Quotes,
  Star,
  Shield,
  Trophy,
  Certificate,
  Phone,
  Envelope,
  WhatsappLogo,
  CaretRight,
  List,
  Calculator,
  Clipboard,
  ArrowClockwise,
  Lightning,
  House,
  ChatCircle,
  MagnifyingGlass,
  Sun,
  Moon,
} from "@phosphor-icons/react";

export const Icons = {
  Wrench: ({ className = "w-7 h-7" }: { className?: string }) => <Wrench className={className} weight="regular" />,
  ShowerHead: ({ className = "w-7 h-7" }: { className?: string }) => <Shower className={className} weight="regular" />,
  DropletSearch: ({ className = "w-7 h-7" }: { className?: string }) => (
    <span className={`relative inline-flex ${className}`}>
      <Drop className="absolute inset-0" weight="regular" />
      <MagnifyingGlass className="relative z-10" weight="bold" />
    </span>
  ),
  Building: ({ className = "w-7 h-7" }: { className?: string }) => <Building className={className} weight="regular" />,
  Flame: ({ className = "w-7 h-7" }: { className?: string }) => <Flame className={className} weight="regular" />,
  Wind: ({ className = "w-7 h-7" }: { className?: string }) => <Wind className={className} weight="regular" />,
  Filter: ({ className = "w-7 h-7" }: { className?: string }) => <Funnel className={className} weight="regular" />,
  AlertTriangle: ({ className = "w-7 h-7" }: { className?: string }) => <Warning className={className} weight="regular" />,
  MapPin: ({ className = "w-5 h-5" }: { className?: string }) => <MapPin className={className} weight="regular" />,
  Quote: ({ className = "w-8 h-8" }: { className?: string }) => <Quotes className={className} weight="regular" />,
  Star: ({ className = "w-4 h-4" }: { className?: string }) => <Star className={className} weight="fill" />,
  Shield: ({ className = "w-7 h-7" }: { className?: string }) => <Shield className={className} weight="regular" />,
  Award: ({ className = "w-7 h-7" }: { className?: string }) => <Trophy className={className} weight="regular" />,
  Certificate: ({ className = "w-7 h-7" }: { className?: string }) => <Certificate className={className} weight="regular" />,
  WaterDrop: ({ className = "w-7 h-7" }: { className?: string }) => <Drop className={className} weight="regular" />,
  Phone: ({ className = "w-5 h-5" }: { className?: string }) => <Phone className={className} weight="regular" />,
  Mail: ({ className = "w-5 h-5" }: { className?: string }) => <Envelope className={className} weight="regular" />,
  WhatsApp: ({ className = "w-6 h-6" }: { className?: string }) => <WhatsappLogo className={className} weight="fill" />,
  ChevronRight: ({ className = "w-5 h-5" }: { className?: string }) => <CaretRight className={className} weight="regular" />,
  Menu: ({ className = "w-7 h-7" }: { className?: string }) => <List className={className} weight="regular" />,
  Calculator: ({ className = "w-7 h-7" }: { className?: string }) => <Calculator className={className} weight="regular" />,
  Clipboard: ({ className = "w-7 h-7" }: { className?: string }) => <Clipboard className={className} weight="regular" />,
  RefreshCw: ({ className = "w-7 h-7" }: { className?: string }) => <ArrowClockwise className={className} weight="regular" />,
  Zap: ({ className = "w-7 h-7" }: { className?: string }) => <Lightning className={className} weight="regular" />,
  Home: ({ className = "w-7 h-7" }: { className?: string }) => <House className={className} weight="regular" />,
  MessageCircle: ({ className = "w-7 h-7" }: { className?: string }) => <ChatCircle className={className} weight="regular" />,
  Sun: ({ className = "w-5 h-5" }: { className?: string }) => <Sun className={className} weight="regular" />,
  Moon: ({ className = "w-5 h-5" }: { className?: string }) => <Moon className={className} weight="regular" />,
};
